### ISSUE TITLE
Presenting a launch screen right after the app was downloaded from the store  

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#1]
The screen will include a small video in the background - https://www.dropbox.com/s/lrhyduuv3f5a05i/Nurse%20meets%20patient.mov?dl=0 

A header "Welcome To medflyt" + The company's logo 

A small flag for choosing the language with a menu picker to choose from the following: english, spanish, portuguese. 

A big sign in-button. Pressing the sign-in button takes the user to the next screen of the regisration process. 

![image](https://cloud.githubusercontent.com/assets/3400052/18493833/3eecea80-7a1b-11e6-8ba0-d48bdae96740.png)

**Comment by amironi** [comment]
Done.

**Comment by amironi** [comment]
Now i can close it:)
