### ISSUE TITLE
User should be able to see the visit details

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#11]
The following fields should be presented to the user: 
Visit date
Visit time 
Visit Price 
Distance 
Map of the visit location 
Time to the visit
Here's a preview of the screen: 

![image](https://cloud.githubusercontent.com/assets/3400052/19163321/2cd8ecf4-8c04-11e6-9673-3f76b7f7be6c.png)

Here's the full PSD file of the screen: 
https://www.dropbox.com/sh/aqv1n1nxhw6tron/AABHQVWUeJhTN8BRfY3Wd4g6a/Medflyt-Visit%20Details?dl=0&preview=Medflyt-EventDetails03.psd

**Comment by liadlivnat** [comment]
HTML is ready, moving to yaniv for ionic implementation

**Comment by omershotvibe** [comment]
The chat icon that you used is covering the bottom line of the transpiration icons, it should be a little bit higher: 

![img_3933](https://cloud.githubusercontent.com/assets/3400052/19240313/7fd5f7c4-8f12-11e6-8128-ce9c6feea6a0.JPG)

**Comment by liadlivnat** [comment]
@omershotvibe @amironi added new button, so should we remove this one?

**Comment by omershotvibe** [comment]
@liadlivnat - I Don't understand what you mean...
