### ISSUE TITLE
Landing Screen - The app should have a landing screen before the phone number screen 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#15]
Landing Screen - The app should have a landing screen before the phone number screen. 

The screen should have a video - this is the link of the video - https://www.dropbox.com/s/lrhyduuv3f5a05i/Nurse%20meets%20patient.mov?dl=0 

We need to prepare a smaller version of the video, sort of an APNG, and to put on top of a sort of a blue/black mask with 30% opacity. 

Then - we need a big button - "Start Here".

When clicking the button the user is taken to the Phone Number typing screen.

**Comment by liadlivnat** [comment]
@omershotvibe Page was added moving back to you.
