### ISSUE TITLE
Profile page should contain  different "cards" to allow him to update all his information about the 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#16]
@liadlivnat @yanivmualem @amironi @IgorPai @MedFlyt/hexsis 

Each card will show the user details as uploaded by him and a small pencil icon will allow the caregiver to upload/edit to  different details about herself: 

The default mode will be to present the user’s details 

Card 1 - General details: 

First name - Simply present the user details as he typed them

Last name - Simply present the user details as he typed them

Email - Simply present the user details as he typed them

Phone number -Non editable field (!) - Simply present the user 
details as he typed them

home number - Simply present the user details as he typed them

Address - Simply present the user details as he typed them 
This should be a google auto complete field

Birthdate - Put a menu picker that will allow the caregiver to select his birthdate. 

Professional type - Put a menu picker that will allow the caregiver to select his type: 
This is the menu picker options: 
RN - Registered Nurse
LPN - Licensed Practical Nurse
CNA - Certified Nurse Assistant
PT - Physical Therapist
OT - Occupational Therapist
ST - Speech Therapist
HHA - Home Health Aid
PCA - Personal Care Assistant

Joined date - Non editable field (!) This field should be taken directly from the server. 

Card 2 - HR Documents: 

Orientation completed 5 out 0f 7 - Non editable field (!). We need to add a small button on the right side of the screen - Orientation, That will open another screen.. 

License certificate number  - Simply present the user details as he typed them

SSN number - Simply present the user details as he typed them

ID scan - here, we’re not presenting the ID scan, we’re only putting a button “view” - when the user clicks it, we’re opening a new screen, presenting the PDF file. 

Certificate scan - here, we’re not presenting the ID scan, we’re only putting a button “view” - when the user clicks it, we’re opening a new screen, presenting the PDF file. 

Insurance card scan- here, we’re not presenting the ID scan, we’re only putting a button “view” - when the user clicks it, we’re opening a new screen, presenting the PDF file. 

Resume - here, we’re not presenting the ID scan, we’re only putting a button “view” - when the user clicks it, we’re opening a new screen, presenting the PDF file. 

Card 3 - Medical Forms:

Medical form from doctor - here, we’re not presenting the ID scan, we’re only putting a button “view” - when the user clicks it, we’re opening a new screen, presenting the PDF file. 

Medical form flu shot - here, we’re not presenting the ID scan, we’re only putting a button “view” - when the user clicks it, we’re opening a new screen, presenting the PDF file. 

Card 4 - Billing:

Card holder name - Only show the last for digits of the credit card
Credit card No. - show the details 
Expire date - show the details 
CCV -- show the details
Subscription model  - Non editable field (!)
Show the text - $4.99 Per scheduled visit

Here's how a "card" looks like: 
![image](https://cloud.githubusercontent.com/assets/3400052/19187045/01db254c-8c92-11e6-84f1-04a9cfb18f3d.png)

here's the PSD file of this screen: 
https://www.dropbox.com/sh/aqv1n1nxhw6tron/AACnkoJDPWnhRRK7d93h9w4Ma/Medflyt-Profile?dl=0&preview=Medflyt-Profile.psd

**Comment by omershotvibe** [comment]
This is the edit mode for this screen: 
![image](https://cloud.githubusercontent.com/assets/3400052/19219796/d59b60c4-8e25-11e6-99a8-d040f41777d9.png)

this is the PSD: 
https://www.dropbox.com/sh/aqv1n1nxhw6tron/AACnkoJDPWnhRRK7d93h9w4Ma/Medflyt-Profile?dl=0&preview=Medflyt-ProfileEdit01.psd

**Comment by liadlivnat** [comment]
@omershotvibe fixed, moving to you, now @amironi should use the templates and add data into them

**Comment by omershotvibe** [comment]
@amironi - let's finish this tomorrow
