### ISSUE TITLE
User should be able to see the list of pending visit that were submitted by the coordinators

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#18]
User should be able to see the list of pending visit that were submitted by the coordinators

The required fields for each visit are the following: 
- Visit area 
- The referring agency 
- Day, Date, Time 
- reimbursement
- A small thumbnail of a map showing the patient's location 

When the user clicks a specific case, it'll open the "visit details" screen - showing the details about the visit. 

The hover effect should have the following color: #..........  

This is how the screen should look like: 
![image](https://cloud.githubusercontent.com/assets/3400052/19230888/92267652-8edf-11e6-9b4b-ee577ed0e7b0.png)

This is the PSD: 
https://www.dropbox.com/sh/aqv1n1nxhw6tron/AAAfClvtu-nC7E_8aso05q2Ua/Pending?dl=0&preview=Medflyt-Pending04.psd

**Comment by omershotvibe** [comment]
There are spaces that needs to be removed: 

![img_3929](https://cloud.githubusercontent.com/assets/3400052/19240084/7c6ca8f4-8f11-11e6-91dd-9aba86ef7372.JPG)
![Uploading IMG_3930.JPG…]()

**Comment by omershotvibe** [comment]
![img_3930](https://cloud.githubusercontent.com/assets/3400052/19240104/9498e37a-8f11-11e6-9761-94c256893648.JPG)

**Comment by omershotvibe** [comment]
1. The Medflyt logo at the top should be lowered
2. The Hamburger menu used isn't correct, it's too thin. the designer used a much thicker hamburger menu. 
3. The Text of the words "Scheduled and "Pending" should always be white, not grey: 

![fullsizerender](https://cloud.githubusercontent.com/assets/3400052/19240198/013f8920-8f12-11e6-9dd9-e2bfff25587e.jpg)

**Comment by liadlivnat** [comment]
fixed, assign back to you @omershotvibe
