### ISSUE TITLE
In the activation screen  on Hover - the button can be with the blue color #3599f6 and the text with white:

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#19]
In the activation screen  on Hover - the button can be with the blue color #3599f6 and the text with white:

![image](https://cloud.githubusercontent.com/assets/3400052/19268602/0223d150-8fbe-11e6-911a-7d60c370af53.png)

**Comment by liadlivnat** [comment]
fixed
