### ISSUE TITLE
when the address of the visit is made of two line - the "+" sign in the middle of the heart doesn't appear properly 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#23]
when the address of the visit is made of two line - the "+" sign in the middle of the heart doesn't appear properly 

![image](https://cloud.githubusercontent.com/assets/3400052/19332938/7d48f388-90f9-11e6-8858-a623ce929950.png)

**Comment by liadlivnat** [comment]
fixed
