### ISSUE TITLE
The keyboard isn't open and ready to type in the "type your phone screen" 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#25]
The keyboard isn't open and ready to type in the "type your phone screen" 
It should be focused 

![image](https://cloud.githubusercontent.com/assets/3400052/19333042/85a1c086-90fa-11e6-876a-6dac993c8730.png)

When the screen appears - it should immediately be like this: 
![image](https://cloud.githubusercontent.com/assets/3400052/19333050/a74a2174-90fa-11e6-99f6-f940a7d4b947.png)

**Comment by liadlivnat** [comment]
fixed

**Comment by omershotvibe** [comment]
Not in iPhone

**Comment by liadlivnat** [comment]
@omershotvibe  regarding showing the keyboard on iPhone, ionic keyboard plugin doesn’t support that.
https://github.com/driftyco/ionic-plugin-keyboard
