### ISSUE TITLE
The hint text in the "type your phone screen" is misdisplaced and a wrong color.. 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#26]
The hint text in the "type your phone screen" is misdisplaced and a wrong color.. 

![image](https://cloud.githubusercontent.com/assets/3400052/19333087/16f87b7e-90fb-11e6-94da-a036ff26e7ed.png)

**Comment by liadlivnat** [comment]
@omershotvibe fixed

**Comment by omershotvibe** [comment]
@liadlivnat In my ionic view it's still the same, here's a screenshot: 
![image](https://cloud.githubusercontent.com/assets/3400052/19358092/2695561a-917d-11e6-81d1-c4fbb170785d.png)
But the color is fine now

**Comment by liadlivnat** [comment]
reproduce only on iphone

**Comment by liadlivnat** [comment]
fixed.

**Comment by omershotvibe** [comment]
Screenshots from latest version: 
1. Hint text should be grey
2. When typing the text it should be white 
![img_4046](https://cloud.githubusercontent.com/assets/3400052/19406387/82da045a-928d-11e6-8191-7f13f8aa6d0c.PNG)
![img_4047](https://cloud.githubusercontent.com/assets/3400052/19406390/8e191da6-928d-11e6-8406-2672fb0fd15d.PNG)


On Android - The line of the area code and the phone aren't aligned:

![2016-10-14 22 57 02](https://cloud.githubusercontent.com/assets/3400052/19406405/acc24c82-928d-11e6-9682-46e4621f55b0.png)
![2016-10-14 23 18 00](https://cloud.githubusercontent.com/assets/3400052/19406407/acc4df88-928d-11e6-847e-47cc1021f8ae.png)
![2016-10-15 00 01 02](https://cloud.githubusercontent.com/assets/3400052/19406406/acc429b2-928d-11e6-9612-0cfbdd73787e.png)
![2016-10-15 00 01 31](https://cloud.githubusercontent.com/assets/3400052/19406408/acc66d08-928d-11e6-87dd-2f57d9e72f18.png)

**Comment by liadlivnat** [comment]
issues fixed @omershotvibe
