### ISSUE TITLE
The keyboard isn't open and ready to type in the "type the verification code" screen  

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#27]
The keyboard isn't open and ready to type in the "type the verification code" screen  

![image](https://cloud.githubusercontent.com/assets/3400052/19333104/4dde2be8-90fb-11e6-9f9d-02ba7663e377.png)

**Comment by liadlivnat** [comment]
fixed

**Comment by omershotvibe** [comment]
Not in iPhone

**Comment by omershotvibe** [comment]
@liadlivnat - Keyboard is missing (Android): 
![2016-10-16 10 31 05](https://cloud.githubusercontent.com/assets/3400052/19416900/2b5ae414-93a6-11e6-9731-2a33f93f8534.png)

**Comment by liadlivnat** [comment]
@omershotvibe  issue fix, it won't work on iphone...
