### ISSUE TITLE
The sentence "Didn't receive any code yet?... " has typos and is misdisplaced  

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#28]
1. The correct way to write it is the following: "Didn't receive any code yet? Press here" 
2. The "press here" should be bold. 
3. The rule is that the location should always be a little bit on top of the keyboard... No matter which phone we're using... Always just a liitle bit on top of the keyboard.

**Comment by liadlivnat** [comment]
fixed

**Comment by omershotvibe** [comment]
@liadlivnat , Now it's completely broken... Here's a screenshot: 

![image](https://cloud.githubusercontent.com/assets/3400052/19358421/8869e1b6-917e-11e6-8f94-ae80e2a55c26.png)

**Comment by liadlivnat** [comment]
i'm not sure how do you see that but it doesn't reproduce, can you check the new version again?

**Comment by liadlivnat** [comment]
reproduce on iphone

**Comment by liadlivnat** [comment]
fixed

**Comment by omershotvibe** [comment]
Just updated to the latest version, and it's not working on my iPhone...

**Comment by omershotvibe** [comment]
screenshots from latest version + The error text is misdisplaced 
![img_4048](https://cloud.githubusercontent.com/assets/3400052/19406333/a14cbd84-928c-11e6-8856-4cb655c241ab.PNG)
![img_4049](https://cloud.githubusercontent.com/assets/3400052/19406334/a2622128-928c-11e6-94cc-f88a83ea0bc8.PNG)
![img_4050](https://cloud.githubusercontent.com/assets/3400052/19406335/a91bd3f6-928c-11e6-929e-3d909b97f58c.PNG)

**Comment by liadlivnat** [comment]
on iphone error message not close to the line, and the next button is not centred.
