### ISSUE TITLE
Keyboard focus also with the "user details"

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#29]
Keyboard focus also with the "user details"

**Comment by liadlivnat** [comment]
@omershotvibe please give more information, i don't understand what we should do here.

**Comment by omershotvibe** [comment]
![image](https://cloud.githubusercontent.com/assets/3400052/19350571/fa0a7b1e-9160-11e6-856e-cfdb324314ea.png)
The keyboard should be presented

**Comment by omershotvibe** [comment]
@liadlivnat Please let me know if you understand...

**Comment by liadlivnat** [comment]
fixed.

**Comment by omershotvibe** [comment]
Not in iPhone

**Comment by liadlivnat** [comment]
@omershotvibe  After i checked, the keyboard cannot be open automatically on iphone - sorry
