### ISSUE TITLE
Registration Process - Step 2: Type your verification code 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#3]
When the user clicks the "Next" button - The apps calls Twilio to send the user a verification code.  The verification will be clicked by the user in the next screen. 

The keyboard should be open all the time 

A big "Next" button will take the user to the next screen. 

![image](https://cloud.githubusercontent.com/assets/3400052/18495152/327f7e08-7a24-11e6-9f75-72bc134fb784.png)

**Comment by omershotvibe** [comment]
i@liadlivnat @MedFlyt/hexsis 
the circles aren't shown
there is an error message when the user types the wrong code 
the keyboard should be always open 

this is the how the screen should look like: 
![image](https://cloud.githubusercontent.com/assets/3400052/19158875/fd05f87a-8bf2-11e6-930c-5e78884c5e05.png)

and this is the error message: 
![image](https://cloud.githubusercontent.com/assets/3400052/19158887/07769a9e-8bf3-11e6-9a9a-ebc6847295e3.png)


the full PSD files are here: 
https://www.dropbox.com/sh/aqv1n1nxhw6tron/AABuyPztsRZdzh0mxGhzww3za/Medflyt-Activation/PSDs?dl=0&preview=Medflyt-ActivationStepB02error.psd

https://www.dropbox.com/sh/aqv1n1nxhw6tron/AABuyPztsRZdzh0mxGhzww3za/Medflyt-Activation/PSDs?dl=0&preview=Medflyt-ActivationStepB02.psd

**Comment by liadlivnat** [comment]
This task was cancel, i move it back to you @omershotvibe
