### ISSUE TITLE
In the "Take a photo screen" The user has no access to the gallery, only to the camera 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#30]
In the "Take a photo screen" The user has no access to the gallery, only to the camera

**Comment by liadlivnat** [comment]
@amironi assigned to you as we don't do the ionic after our conversation with @omershotvibe

**Comment by omershotvibe** [comment]
@liadlivnat This is what @amironi wrote me:
שיכין את הui לבחירה בין מצלמה לגלריה ואני אממש את הגלריה...

**Comment by omershotvibe** [comment]
@liadlivnat - Who's taking this issue under responsibility?

**Comment by liadlivnat** [comment]
we added the menu and connected it to the camera, now @amironi needs to connect it to the gallery.

**Comment by amironi** [comment]
done.
