### ISSUE TITLE
All over the login process, The "next" button isn't bordered in the same line as in the design 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#32]
All over the login process, The "next" button isn't bordered in the same line as in the design 
In the designs, the line is much thicker. 

I'd like to stick to the design.

**Comment by liadlivnat** [comment]
fixed

**Comment by omershotvibe** [comment]
@liadlivnat The button isn't centered All over the login process... It's aligned to the left..

**Comment by liadlivnat** [comment]
@omershotvibe i just pushed some changes and haven't seen that, can you check again the new version?

**Comment by omershotvibe** [comment]
@liadlivnat - doesn't work on iPhone... Only in Android

**Comment by liadlivnat** [comment]
@omershotvibe what do you mean it doesn't work on iphone? it's a style? the buttons are like the design now. please re-check.
