### ISSUE TITLE
Event details screen - We have a serious size problem 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#35]
The way it's presented in the design and in the live app is completely different - 
The entire purpose of the design was to show all the information in one screen, without the need to scroll down... The scroll down generates a serious problem, because when the user puts his finger on the map trying to scroll down - then the map moves... Instead of scrolling the screen, and the user gets confused... 

This is how it looks on our app: 
iOS, And Android: 

![image](https://cloud.githubusercontent.com/assets/3400052/19333789/201c403c-9100-11e6-84cb-019310843a97.png)

![2016-10-13-photo-00000040](https://cloud.githubusercontent.com/assets/3400052/19333796/311d345e-9100-11e6-9369-970681cfb6f7.jpg)

And this is how is should actually look like: 

![img_3980](https://cloud.githubusercontent.com/assets/3400052/19333610/d8d55236-90ff-11e6-9e6f-a0d907919142.PNG)

**Comment by liadlivnat** [comment]
@omershotvibe fixed
