### ISSUE TITLE
The profile view page - the design and the view in the app doesn't match 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#36]
I believe we're using a larger or a different font then she's actually using in her design... 

This is the design:
![image](https://cloud.githubusercontent.com/assets/3400052/19333932/299a0512-9101-11e6-9e5b-805f7c451c67.png)

And this is our app: 

![image](https://cloud.githubusercontent.com/assets/3400052/19333934/2ec60fa4-9101-11e6-89dd-f0ea13b530df.png)

You can see the difference clearly here: 

![image](https://cloud.githubusercontent.com/assets/3400052/19333958/55003c3a-9101-11e6-9a4a-7f99283b7b4d.png)

**Comment by liadlivnat** [comment]
fixed
