### ISSUE TITLE
The list of scheduled screen is buggy - shows only half of the visit... 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#37]
This is how it appears in the top of the screen - You only see a bunch of visit: 

![image](https://cloud.githubusercontent.com/assets/3400052/19390409/ade0bb2e-9230-11e6-9c4e-be6fd866c8b7.png)

But then, you suddenly see a list of other visits, and the elements looks buggy... 

![image](https://cloud.githubusercontent.com/assets/3400052/19390424/ba735c84-9230-11e6-92af-5d2c17d5f977.png)

![image](https://cloud.githubusercontent.com/assets/3400052/19390427/bddf5508-9230-11e6-83ec-d09aaaac5761.png)

![image](https://cloud.githubusercontent.com/assets/3400052/19390427/bddf5508-9230-11e6-83ec-d09aaaac5761.png)

**Comment by liadlivnat** [comment]
@amironi can you add me some data to 0544302040 in order to reproduce that?

**Comment by liadlivnat** [comment]
Can't reproduce seems like resolved, can you check @omershotvibe
