### ISSUE TITLE
Registration Process - Step 3: Type your user details 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#4]
The screen will present to the user two empty fields that needs to filled: 
First Name, Last name

The keyboard should be constantly open. 

When clicking the "next" button the user is taken to the next screen - where he can set his profile picture.

**Comment by omershotvibe** [comment]
@amironi @liadlivnat @yanivmualem @MedFlyt/hexsis 

The keyboard should be always open, like this: 

![image](https://cloud.githubusercontent.com/assets/3400052/19158964/5af4ff76-8bf3-11e6-9ce4-5c24dd8decca.png)


The error message isn't appearing. 

The address field should use the Google auto complete. 
Once the user focuses with his finger on the address field, the entire screen should go up a little bit, to allow the auto complete feature to present the suggestions of the addresses. The user should be able to click the address he desires and the address will appear in the line, the screen will go back down and then the user will clicks the "next" button and his forwarded to the profile picture screen

**Comment by liadlivnat** [comment]
This task moved to @amironi

**Comment by amironi** [comment]
goole auto comlete done.
please add css class for error. as above

**Comment by omershotvibe** [comment]
task moves back to @liadlivnat
