### ISSUE TITLE
Registration Process - Step 4: User sets the profile picture 

### ISSUE THREAD

**Issue by omershotvibe** [MedFlyt/medflyt_mobile#5]
This screen will allow the user to set his profile photo. 

Once the screen is presented, a big empty space in the middle with an open camera allows the user to take a photo of himself. 

The user can choose if he wants to take photos for the gallery as well. 

Once the user has decided which photo he wants - the photo will be kept in our DB and server for later and the user can click next to move to the next screen. 

![image](https://cloud.githubusercontent.com/assets/3400052/18495232/06da7c70-7a25-11e6-90c0-3bcbe8e1279e.png)

**Comment by omershotvibe** [comment]
@amironi @liadlivnat @yanivmualem @MedFlyt/hexsis 

After the user details screen we should have another screen to let the user set his profile photo - 
When the user clicks the camera icon in the middle of the screen - it should pop up a native OS message asking him: 
1. ) From camera 
2. ) From gallery

And the user will be able to take a photo using the native camera, or to upload a photo from the gallery. 

The photo should be kept in the server and in the database and should always be presented in the user's future log-ins

**Comment by omershotvibe** [comment]
@liadlivnat @yanivmualem @IgorPai 
This is how the screen will look like: 
![image](https://cloud.githubusercontent.com/assets/3400052/19219171/ee91f1b2-8e14-11e6-89a3-27a076ccd0ef.png)

This is the full PSD 
https://www.dropbox.com/sh/aqv1n1nxhw6tron/AABuyPztsRZdzh0mxGhzww3za/Medflyt-Activation/PSDs?dl=0&preview=MedflytActivationCamera02.psd

**Comment by liadlivnat** [comment]
@omershotvibe page is done moving back to you
